import { Metadata } from 'next';

export const metadata: Metadata = {
  title: {
    default: 'Next.js - Doyu', // title을 지정하지 않은 자식 경로에 대한 fallback 역할
    template: '%s | Doyu', // title에 일관된 접두사나 접미사를 추가하려고 할 때
    // absolute: '', // 부모 세그먼트에서 설정한 template 패턴에서 벗어나고 싶을 때
  },
  description: 'Generated by Next.js',
};

export default function MainLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: 'lightblue', padding: '1rem' }}>
          <p>Header</p>
        </header>
        {children}
        <footer style={{ backgroundColor: 'ghostwhite', padding: '1rem' }}>
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
